### ISSUE TITLE
SQLMap

### ISSUE THREAD

**Issue by syogod** [CountablyInfinite/oscp_cheatsheet#1]
Just FYI, sqlmap isn't allowed for OSCP. Might warrant a warning on the sqlmap section.

https://help.offensive-security.com/hc/en-us/articles/360046869951-OSWE-Exam-Guide

**Comment by CountablyInfinite** [comment]
I am aware of that and agree with you. I will add a short warning, thanks.

**Comment by CountablyInfinite** [comment]
Updated cheatsheet and cherry tree file with a disclaimer on tool usage.
